baseurl = "https://dimitri-justeau.github.io/" 
builddrafts = false
canonifyurls = true
contentdir = "content"
DefaultContentLanguage = "en"
layoutdir = "layouts"
publishdir = "public"
author = "Dimitri Justeau"
title = "{ Dimitri Justeau }"
pygmentsuseclasses = true
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
author = "{ Dimitri Justeau }"
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Don't panic"
email = "dimitri.justeau@gmail.com"
# faviconfile = "img/leaf.ico"
github = "//github.com/dimitri-justeau"
linkedin = "//linkedin.com/in/dimitrijusteau"

extracssfiles = [ "/css/override.css" ] # In your `static/css`, add/remove files as necessary.

[Languages]
[Languages.en]

[Languages.fr]

[Languages.es]

