baseURL = "https://dimitri-justeau.github.io"
languageCode = "en"
defaultContentLanguage = "en"
title = "Dimitri Justeau"
enableRobotsTXT = true
enableEmoji = true
theme = "even"

paginate = 3
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = "Dimitri Justeau"
[author]
  name = "Dimitri Justeau"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[params]
  since = "2017"            # Site creation time

  # site info (option)
  logoTitle = "Dimitri Justeau"        # default: the title value
  keywords = ["Hugo", "theme","even"]
  description = "Hi, I am Dimitri! Currently PhD candidate, I use applied mathematics and computer science to solve conservation planning problems. This is my personal website, where you can learn more about me and my projects. I also use it as a PhD blog, and post about science and tech stuff."

  # paginate of archives, tags and categories
  archive-paginate = 3
  
  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?
  moreMeta = false

  # Some global options, you can close something in front matter.
  toc = true
  fancybox = true           # see https://github.com/fancyapps/fancybox
  mathjax = true            # see https://www.mathjax.org/
  linkToMarkDown = false    # if you config contentCopyright and hugo output .md files.

  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  [params.publicCDN]        # load these files from public cdn
    enable = false
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJs = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCss = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'

  [params.reward]
    enable = false
    wechat = "/path/to/your/wechat-qr-code.png"
    alipay = "/path/to/your/alipay-qr-code.png"

  [params.social]
    a-email = "mailto:dimitri.justeau@gmail.com"
    b-stack-overflow = "https://stackoverflow.com/users/5131997/dim"
    e-linkedin = "https://www.linkedin.com/in/dimitrijusteau/"
    g-github = "https://github.com/dimitri-justeau"

# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffix = "md"
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
